name: Run Tests

on:
  push:
    branches:
      - TASK-7  

jobs:
  Go-Tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.19'  

    - name: Install dependencies
      run: go mod tidy

    - name: Run tests in specific packages
      run: |
        go test ./path/to/package1 ./path/to/package2  # Укажите пути к вашим пакетам