run:
  timeout: 5m
  tests: false

linters:
  enable-all: true
  disable:
    - exportloopref
    - maligned
    - varnamelen
    - forbidigo
    - goimports
  fast: false

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/IDevFrye/task-6)
    skip-generated: false
    custom-order: true
  depguard:
    rules:
      main:
        files:
          - !$test
        allow:
          - $gostd
          - 'github.com/mdlayher/wifi'
          
