input-file: "D:/lets-go-programming-v2024-autumn-spbstu/ann.kozakova/task-3/internal/source/1.xml"
output-file: "D:/lets-go-programming-v2024-autumn-spbstu/ann.kozakova/task-3/internal/result/output.json"