name: Go

on:
  push:
    branches: [ "elina-klebleeva-task-7" ]

jobs:
  Go-Tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.23

    - name: database
      working-directory: ./internal/db
      run: go test -v ./...
      
    - name: wifi
      working-directory: ./internal/wifi
      run: go test -v ./...