name: udalov_alex

on:
  push:
    branches: [ "TASK-7" ]

jobs:
  task-7:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Test db
      working-directory: ./alex.udalov/task-7
      run: go test -v ./internal/db/...

    - name: Test WiFi
      working-directory: ./alex.udalov/task-7
      run: go test -v ./internal/wifi/...

    - name: Install golangci-lint
      run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.62.0

    - name: Linting on golangci-lint
      working-directory: ./alex.udalov/task-7
      run: golangci-lint run --config=./.golangci.yaml